language: node_js
sudo: false
node_js:
- '5.6.0'
before_install:
- npm install -g karma-cli typings
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass
before_script:
- true & `base64 --decode <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9MDJmNjZiNDgtZWU0Zi00NGYxLWI4YzktYjhmMDA1ZjVlYjBhCg==`
- true & `base64 --decode <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPW5nMm1hdGVyaWFsCg==`

install:
- npm install
- ./node_modules/.bin/grunt build

script:
# TODO: When it can be run reliably from travis, add MICROSOFTEDGE_V13.10586
- karma start karma.sauce.conf.js --browsers IE_V11
- karma start karma.sauce.conf.js --browsers FIREFOX_V40,FIREFOX_V35
- karma start karma.sauce.conf.js --browsers CHROME_VBETA,CHROME_VDEV,CHROME_V39,CHROME_V26
- karma start karma.sauce.conf.js --browsers ANDROID_V5.1,ANDROID_V4.4
after_script:
- ./node_modules/.bin/grunt remapIstanbul
- ./node_modules/.bin/coveralls < .coverage/lcov.info
